### ISSUE TITLE
增加字体渲染设置

### ISSUE THREAD

**Issue by 5kyfkr** [Zuoqiu-Yingyi/siyuan-plugin-custom-fonts#19]
大佬您好，下面是我自己改的字体渲染片段，搭配你的插件一起感觉很好用，感觉可以集成进去让更多人用上，一些踩过的坑在这https://github.com/siyuan-note/siyuan/issues/10902
```css
:not(.katex):not(.overlaydiv):not([class*="icon"]):not([class*="button"]){
 /*使字体渲染不会应用于部分特殊字符符号和图标以及按钮等网页元素*/
    text-shadow: 0.01em 0.01em 0.01em #999999 ;  
 /*更改字体阴影及透明度,可修改数值实现不同的效果.*/
    -webkit-text-stroke-width: 0.10px;
    -webkit-font-smoothing: antialiased;
    text-rendering: optimizeLegibility;
}

 /*使字体渲染不会应用于公式和图片制卡*/
span:not([class="katex"]) :not([class="overlaydiv"]){
    text-shadow: 0.01em 0.01em 0.01em rgba(0,0,0,0) !important;  
}

 /*使字体渲染不会应用于加粗字体*/
.b3-typography strong, .b3-typography span[data-type~=strong], .protyle-wysiwyg strong, .protyle-wysiwyg span[data-type~=strong] {
    text-shadow: 0.01em 0.01em 0.01em #999999 !important;  
    -webkit-text-stroke-width: 0px !important;
}
```
